_wandb:
    value:
        cli_version: 0.30.0
        e:
            07n3f87351ut36b6m1bbbi42cmlkhrtw:
                email: arauujojulia@outlook.com
                executable: C:\Users\silva\PycharmProjects\PythonProject\.venv\Scripts\python.exe
                host: DESKTOP-2VNMGFT
                os: Windows-10-10.0.19045-SP0
                program: -m ml.train
                python: CPython 3.14.5
                root: C:\Users\silva\PycharmProjects\PythonProject
                startedAt: "2026-09-19T02:24:36.085078Z"
                writerId: 07n3f87351ut36b6m1bbbi42cmlkhrtw
        m: []
        python_version: 3.14.5
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.14.5
            "5": 0.30.0
            "8":
                - 3
            "10":
                - 20
            "12": 0.30.0
            "13": windows-amd64
C:
    value: 1
class_weight:
    value: null
dual:
    value: false
fit_intercept:
    value: true
intercept_scaling:
    value: 1
l1_ratio:
    value: 0
max_iter:
    value: 1000
modelo:
    value: regressao_logistica
n_jobs:
    value: null
penalty:
    value: deprecated
random_state:
    value: 42
solver:
    value: lbfgs
test_size:
    value: 0.2
tol:
    value: 0.0001
verbose:
    value: 0
warm_start:
    value: false
