_wandb:
    value:
        cli_version: 0.30.0
        e:
            t9sz86hevdkcsnejvgm8x4smq7ew4ta6:
                cpu_count: 2
                cpu_count_logical: 4
                disk:
                    /:
                        total: "127328075776"
                        used: "60686381056"
                email: arauujojulia@outlook.com
                executable: C:\Users\silva\PycharmProjects\PythonProject\.venv\Scripts\python.exe
                host: DESKTOP-2VNMGFT
                memory:
                    total: "8466989056"
                os: Windows-10-10.0.19045-SP0
                program: -m ml.train
                python: CPython 3.14.5
                root: C:\Users\silva\PycharmProjects\PythonProject
                startedAt: "2026-09-19T02:24:41.838713Z"
                writerId: t9sz86hevdkcsnejvgm8x4smq7ew4ta6
        m: []
        python_version: 3.14.5
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.14.5
            "5": 0.30.0
            "8":
                - 3
            "10":
                - 20
            "12": 0.30.0
            "13": windows-amd64
C:
    value: 1
break_ties:
    value: false
cache_size:
    value: 200
class_weight:
    value: null
coef0:
    value: 0
decision_function_shape:
    value: ovr
degree:
    value: 3
gamma:
    value: scale
kernel:
    value: rbf
max_iter:
    value: -1
modelo:
    value: svm
probability:
    value: true
random_state:
    value: 42
shrinking:
    value: true
test_size:
    value: 0.2
tol:
    value: 0.001
verbose:
    value: false
